// <auto-generated />
using System;
using Infrastructure.RL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.RL.Migrations
{
    [DbContext(typeof(RideLinkerDbContext))]
    [Migration("20240117110158_TripAndReservation")]
    partial class TripAndReservation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            Brand = "Volkswagen",
                            Image = "https://dam.broekhuis.online/online/broekhuis/modelpaginas/volkswagen/image-thumb__29831__original/hero-vw-id3-mob.webp",
                            LocationId = 1,
                            Model = "ID.3"
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            Brand = "Volkswagen",
                            Image = "https://dam.broekhuis.online/online/broekhuis/modelpaginas/volkswagen/image-thumb__29831__original/hero-vw-id3-mob.webp",
                            LocationId = 1,
                            Model = "ID.3"
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            Brand = "Volkswagen",
                            Image = "https://dam.broekhuis.online/online/broekhuis/modelpaginas/volkswagen/image-thumb__29831__original/hero-vw-id3-mob.webp",
                            LocationId = 1,
                            Model = "ID.3"
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            Brand = "Volkswagen",
                            Image = "https://dam.broekhuis.online/online/broekhuis/modelpaginas/volkswagen/image-thumb__29831__original/hero-vw-id3-mob.webp",
                            LocationId = 1,
                            Model = "ID.3"
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            Brand = "Audi",
                            Image = "https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg",
                            LocationId = 1,
                            Model = "E-tron"
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            Brand = "Audi",
                            Image = "https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg",
                            LocationId = 1,
                            Model = "E-tron"
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            Brand = "Audi",
                            Image = "https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg",
                            LocationId = 1,
                            Model = "E-tron"
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            Brand = "Audi",
                            Image = "https://ev-database.org/img/auto/Audi_e-tron/Audi_e-tron-01@2x.jpg",
                            LocationId = 2,
                            Model = "E-tron"
                        });
                });

            modelBuilder.Entity("Core.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Konijnenberg 24",
                            Name = "Breda"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nachtwachtlaan 20",
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Vliegend Hertlaan 39",
                            Name = "Utrecht"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Velperweg 27",
                            Name = "Arnhem"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Brouwerijstraat 1",
                            Name = "Enschede"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Vrijthof 23",
                            Name = "Maastricht"
                        });
                });

            modelBuilder.Entity("Core.Domain.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId", "TripId")
                        .IsUnique();

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TripId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            TripId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            TripId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            TripId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            TripId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            TripId = 6,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            TripId = 7,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            TripId = 8,
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            TripId = 9,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            TripId = 10,
                            UserId = 6
                        },
                        new
                        {
                            Id = 11,
                            TripId = 11,
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            TripId = 12,
                            UserId = 7
                        },
                        new
                        {
                            Id = 13,
                            TripId = 13,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Core.Domain.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("DepartureId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("DriverId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            DepartureId = 1,
                            DestinationId = 2,
                            DriverId = 2,
                            EndTime = new DateTime(2024, 1, 22, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 22, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 1,
                            DepartureId = 2,
                            DestinationId = 1,
                            DriverId = 2,
                            EndTime = new DateTime(2024, 1, 23, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 23, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 2,
                            DepartureId = 1,
                            DestinationId = 5,
                            DriverId = 3,
                            EndTime = new DateTime(2024, 1, 23, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 23, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CarId = 2,
                            DepartureId = 5,
                            DestinationId = 1,
                            DriverId = 3,
                            EndTime = new DateTime(2024, 1, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 27, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CarId = 3,
                            DepartureId = 1,
                            DestinationId = 2,
                            DriverId = 1,
                            EndTime = new DateTime(2024, 1, 27, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 27, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CarId = 4,
                            DepartureId = 1,
                            DestinationId = 6,
                            DriverId = 4,
                            EndTime = new DateTime(2024, 1, 27, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 1, 27, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CarId = 4,
                            DepartureId = 1,
                            DestinationId = 6,
                            DriverId = 4,
                            EndTime = new DateTime(2024, 2, 1, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 2, 1, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CarId = 5,
                            DepartureId = 1,
                            DestinationId = 6,
                            DriverId = 5,
                            EndTime = new DateTime(2024, 1, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 2, 1, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CarId = 5,
                            DepartureId = 6,
                            DestinationId = 4,
                            DriverId = 5,
                            EndTime = new DateTime(2024, 2, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 2, 2, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CarId = 6,
                            DepartureId = 4,
                            DestinationId = 6,
                            DriverId = 6,
                            EndTime = new DateTime(2024, 2, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 2, 2, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CarId = 6,
                            DepartureId = 6,
                            DestinationId = 1,
                            DriverId = 6,
                            EndTime = new DateTime(2024, 2, 2, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 2, 2, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CarId = 8,
                            DepartureId = 2,
                            DestinationId = 5,
                            DriverId = 7,
                            EndTime = new DateTime(2024, 2, 3, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 2, 3, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CarId = 8,
                            DepartureId = 5,
                            DestinationId = 2,
                            DriverId = 7,
                            EndTime = new DateTime(2024, 2, 3, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2024, 2, 3, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MobileNr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@mail.com",
                            Name = "Admin",
                            UserRole = 0
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hg@mail.com",
                            Name = "Hans Gerard",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sten@mail.com",
                            Name = "Sten",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kalle@mail.com",
                            Name = "Kalle",
                            UserRole = 0
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quinn@mail.com",
                            Name = "Quinn",
                            UserRole = 0
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "matthijs@mail.com",
                            Name = "Matthijs",
                            UserRole = 1
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "baraa@mail.com",
                            Name = "Baraa",
                            UserRole = 1
                        });
                });

            modelBuilder.Entity("Core.Domain.Car", b =>
                {
                    b.HasOne("Core.Domain.Location", "Location")
                        .WithMany("Cars")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Core.Domain.Reservation", b =>
                {
                    b.HasOne("Core.Domain.Trip", "Trip")
                        .WithMany("Reservations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Domain.Trip", b =>
                {
                    b.HasOne("Core.Domain.Car", "Car")
                        .WithMany("Trips")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Location", "Departure")
                        .WithMany()
                        .HasForeignKey("DepartureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Location", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.User", "Driver")
                        .WithMany("TripsAsDriver")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Departure");

                    b.Navigation("Destination");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Core.Domain.Car", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Core.Domain.Location", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Core.Domain.Trip", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Core.Domain.User", b =>
                {
                    b.Navigation("TripsAsDriver");
                });
#pragma warning restore 612, 618
        }
    }
}
